name: "Python Test"
description: "Python Test Template"
inputs:
  py:
    required: true
    description: "Target Python Version"
  os:
    required: true
    description: "Target Operating System"
runs:
  using: "composite"
  steps:
    - name: Debug Logging
      shell: ${{ contains(inputs.os, 'windows') && 'pwsh' || 'bash' }}
      run: |
        echo "event  = ${{ github.event_name }}"
        echo "action = ${{ github.event.action }}"
    - name: Set up Python ${{ inputs.py }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.py }}
    - name: Install Dependencies (Linux)
      if: ${{ contains(inputs.os, 'ubuntu') }}
      shell: ${{ contains(inputs.os, 'windows') && 'cmd' || 'bash' }}
      run: sudo apt-get install xclip xvfb
    - name: MacOS-specific dependencies
      if: ${{ contains(inputs.os, 'macos') }}
      shell: bash
      run: brew install libmagic
    - name: Install Dependencies
      shell: ${{ contains(inputs.os, 'windows') && 'cmd' || 'bash' }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install pycodestyle
        pip install .[all]
    - name: Unit Tests
      if: ${{ !contains(inputs.os, 'ubuntu') }}
      shell: ${{ contains(inputs.os, 'windows') && 'cmd' || 'bash' }}
      run: python -m unittest discover -p test_*.py
    - name: Unit Tests
      if: ${{  contains(inputs.os, 'ubuntu') }}
      shell: bash
      run: XDG_SESSION_TYPE=x11 xvfb-run python -m unittest discover -p test_*.py
