name: tests

on:
  push:
    branches: [ master ]
    tags-ignore: '**'
  pull_request:
    types: [opened, synchronize]
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      MALSHARE_API: ${{ secrets.MALSHARE_API }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.12']
        os: [windows-latest, macos-13, ubuntu-latest]
    steps:
      - name: Run Tests
        uses: ./.github/workflows/test-template.yml
        with:
          py: ${{ matrix.python-version }}
          os: ${{ matrix.os }}

  preview:
    continue-on-error: true
    runs-on: 'ubuntu-latest'
    env:
      MALSHARE_API: ${{ secrets.MALSHARE_API }}
    steps:
      - name: Run Tests
        uses: ./.github/workflows/test-template.yml
        with:
          py: '3.13'
          os: 'ubuntu-latest'

  coverage:
    if: ${{ github.repository_owner == 'binref' }}
    runs-on: ubuntu-latest
    needs: test
    env:
      MALSHARE_API: ${{ secrets.MALSHARE_API }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        sudo apt-get install xclip xvfb
        python -m pip install --upgrade pip
        python -m pip install pycodestyle pytest pytest-cov
        pip install .[all]
    - name: Run tests and collect coverage
      run: |
        XDG_SESSION_TYPE=x11 xvfb-run pytest --cov-config=.coveragerc --cov refinery test/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        fail_ci_if_error: true
